id: productQuery
displayName: Product Query
created: '2026-06-09T08:48:44.571163+00:00'
modified: '2026-06-09T08:48:44.571163+00:00'
createdBy: google-oauth2|118138255479849584814
ttl: 30
path: /api/products/get
custom:
  proposedName: Product Query
  selectedCategoryIds: []
  selectedDisplayField: name
method: GET
purgeKey: f2936a43-69fe-49a6-b887-d053740e58ad
archetype: queryProducts
variables:
  page:
    type: text
    default: '1'
    displayName: Page
  limit:
    type: text
    default: ''
    displayName: Limit
  keyword:
    type: text
    default: ''
    displayName: Keyword
  sortField:
    type: text
    default: ''
    displayName: Sort Field
  categoryId:
    type: text
    default: ''
    displayName: Category Id
  productIds:
    type: text
    default: ''
    helpText: Array of product ids
    displayName: Product Ids
  sortDirection:
    type: text
    default: ''
    displayName: Sort Direction
parameters:
  - key: id
    value: ${productIds}
  - key: categoryId
    value: ${categoryId}
  - key: keyword
    value: ${keyword}
  - key: sortField
    value: ${sortField}
  - key: sortDirection
    value: ${sortDirection}
  - key: limit
    value: ${limit}
  - key: page
    value: ${page}
dataSourceId: fakeCommerce
allowedOnComponents: []
